### ISSUE TITLE
Incorrect Mapping from Navigation property in Generated Code

### ISSUE THREAD

**Issue by sumonkrdas** [riok/mapperly#1177] opened 2024-03-15 06:31 UTC
**Describe the bug**
Mapperly incorrectly maps the ProductTypeId property in the LenderDto class, using the Id of the LenderDetail class instead of traversing the property path to obtain the ProductType.Id from the associated Lender.

**Declaration code**
```csharp
[MapProperty(new[] { nameof(LenderDetail.Lender.ProductType.Id) }, new[] { nameof(LenderDto.ProductTypeId) })]
public partial List<LenderDto> Map(IEnumerable<LenderDetail> lenderDetailList);
```
**Source class**
```csharp
public class LenderDetail : AuditableBase
{
    public int Id { get; set; }
    public int LenderId { get; set; }
    public Lender Lender { get; set; }
}
```

**Destination class**
```csharp
public class LenderDto
{
    public int Id { get; set; }
    public int LenderId { get; set; }
    public int ProductTypeId { get; set; }
}
```

**Actual relevant generated code**
```csharp
// Actual relevant code generated by Mapperly
// see also https://mapperly.riok.app/docs/configuration/generated-source/
[global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
public partial global::Model.DTO.Lender.LenderDto Map(global::Domain.LenderDetail lenderDetail)
{
    var target = new global::Model.DTO.Lender.LenderDto();
    target.Id = lenderDetail.Id;
    target.LenderId = lenderDetail.LenderId;
    target.ProductTypeId = lenderDetail.Id; // Incorrect mapping
    return target;
}
```

**Expected relevant generated code**
```csharp
// The generated code how you expect it to look like
// Correct mapping should reference the ProductType.Id through the Lender association
target.ProductTypeId = lenderDetail.Lender.ProductType.Id;
```

**Environment (please complete the following information):**
- Mapperly Version: 3.4.0
- .NET Version:8.0
- Target Framework: 8.0
- IDE:  Visual Studio v17.8.6
- OS: Windows 11

**Comment by latonz** [comment] 2024-03-15 19:53
In your declaration you are applying the `MapProperty` to the mapping of the list. However, the list does not have such a property. Don't you see some RMG* diagnostics emitted?

What you probably want is sth. like this:
```csharp
public partial List<LenderDto> Map(IEnumerable<LenderDetail> lenderDetailList);

[MapProperty(new[] { nameof(LenderDetail.Lender.ProductType.Id) }, new[] { nameof(LenderDto.ProductTypeId) })]
private partial LenderDto Map(LenderDetail lenderDetail);
```

**Comment by sumonkrdas** [comment] 2024-03-16 02:42
> In your declaration you are applying the `MapProperty` to the mapping of the list. However, the list does not have such a property. Don't you see some RMG* diagnostics emitted?
> 
> What you probably want is sth. like this:
> 
> ```cs
> public partial List<LenderDto> Map(IEnumerable<LenderDetail> lenderDetailList);
> 
> [MapProperty(new[] { nameof(LenderDetail.Lender.ProductType.Id) }, new[] { nameof(LenderDto.ProductTypeId) })]
> private partial LenderDto Map(LenderDetail lenderDetail);
> ```

If a property is missing it can give default or null value why its binding with a wrong property?
```cs
target.ProductTypeId = lenderDetail.Id; // Incorrect mapping
```

**Comment by latonz** [comment] 2024-03-17 20:09
The problem is that `nameof(LenderDetail.Lender.ProductType.Id)` resolves to `Id`.
Your
```csharp
[MapProperty(new[] { nameof(LenderDetail.Lender.ProductType.Id) }, new[] { nameof(LenderDto.ProductTypeId) })]
```
becomes
```csharp
[MapProperty(new[] { "Id" }, new[] { "ProductTypeId" })]
```

therefore the mapping
```csharp
target.ProductTypeId = lenderDetail.Id;
```
is correct.

You could simply use the [experimental full-nameof](https://mapperly.riok.app/docs/configuration/flattening/#experimental-full-nameof) to get the correct path name:
```csharp
[MapProperty(nameof(@LenderDetail.Lender.ProductType.Id), nameof(LenderDto.ProductTypeId))]
```

**Comment by cremor** [comment] 2024-03-20 07:43
I had a similar problem recently. It's really easy to forget the `@` symbol and if the property name happens to exist then you won't get a warning for it. Would it be possible for Mapperly to create a warning message if it sees a `nameof` usage with more than one dot in the path, but without the `@` symbol?

**Comment by latonz** [comment] 2024-03-20 20:12
@cremor yes we could do this. I think it should even be possible to get rid of the `@` completely. For this to happen I think we need to improve the fullnameof handling quite a bit with better diagnostics, detecting at which part of the member path the relevant path begins (stripping the class name and possible the namespace), ...

**Comment by latonz** [comment] 2024-03-20 20:13
I'm closing this for now as this should fix the problem: https://github.com/riok/mapperly/issues/1177#issuecomment-2002601814. If the problem still exists feel free to comment.

**Closed by latonz** 2024-03-20 20:13 UTC
Labels: bug
