### ISSUE TITLE
Property specific static mapper

### ISSUE THREAD

**Issue by clintsinger** [riok/mapperly#1096] opened 2024-01-30 01:09 UTC
I have two fields that are the same type but need a different return results.  In my case I have two `int` types but they the need to be transformed to specific sized `BitArray`.   There isn't any way to differentiate these two using conventions from what I could find.   

**Describe the solution you'd like**
Similar to how static mappers work, it would be handy to be able to assign them to specific properties where it is mapped by name rather than types.  

For example, it could look like the following where the name of the conversion method is passed to the property mapper.

```csharp
[MapProperty(nameof(InputClass.SevenBitMask), nameof(OutputClass.SevenBitMask), nameof(SevenBitMaskToBitArray)]
[MapProperty(nameof(InputClass.TwelveBitMask), nameof(OutputClass.TwelveBitMask), nameof(TwelveBitMaskToBitArray)]
public static partial OutputClass Map(InputClass input);

private static BitArray SevenBitMaskToBitArray(int input) => input.ToBitArray(7);

private static BitArray TwelveBitMaskToBitArray(int input) => input.ToBitArray(12);
```

**Describe alternatives you've considered**
I could write a an implementation where I create the entire object myself, but that isn't as nice.

**Comment by latonz** [comment] 2024-01-30 13:54
Duplicate of https://github.com/riok/mapperly/issues/783

**Closed by latonz** 2024-01-30 13:54 UTC
Labels: enhancement
