### ISSUE TITLE
`AttributeDataAccessor` fails to construct `MapEnumValue`

### ISSUE THREAD

**Issue by TimothyMakkison** [riok/mapperly#486] opened 2023-06-07 17:30 UTC
**Describe the bug**
I noticed the benchmarks were only using 6000KB of memory. When I ran `SourceGeneratorBenchmarks.LargeCompile()` I got the following message:

`System.MissingMethodException: Constructor on type 'Riok.Mapperly.Configuration.MapEnumValue' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Riok.Mapperly.Configuration.AttributeDataAccessor.Access[TAttribute,TData](WellKnownTypes knownTypes, ISymbol symbol)+MoveNext() in /_/src/Riok.Mapperly/Configuration/AttributeDataAccessor.cs:line 41
   at Riok.Mapperly.Descriptors.MappingBuilders.EnumMappingBuilder.BuildExplicitValueMapping(MappingBuilderContext ctx) in /_/src/Riok.Mapperly/Descriptors/MappingBuilders/EnumMappingBuilder.cs:line 144`

Bizarrely the integration or unit tests don't fail. I assume this is due to #478 and `MapEnumValue` being both a record type and attribute. This could be caused by `Activator` trying to create `MapEnumValue(TypedConstant, TypedConstant)` from `ctorArguments` where `BuildArgumentValue` have cast the values to integer objects.

**Comment by latonz** [comment] 2023-06-09 07:42
I cannot reproduce this 🤔 Regarding `MapEnumValue`: one is `MapEnumValue` and the other `MapEnumValueAttribute`, so these are not named the same...

**Comment by TimothyMakkison** [comment] 2023-06-12 11:43
The issue is caused by `Activator.CreateInstance` attempting to construct `Configuration.MapEnumValue` using constructor arguments that have been cast from `TypedConstant` into its actual type using `BuildArgumentValue`. Because the constructor is `MapEnumValue(TypedConstant, TypedConstant)` it fails to construct the object from the converted types and fails.

We can prove this by adding a `try catch` statement with a fallback that uses the unconverted arguments to construct `MapEnumValue`.
```C#
TData attr;
try
{
    attr = (TData)Activator.CreateInstance(typeof(TData), newInstanceArguments);
}
catch
{
    var con = attrData.ConstructorArguments.Select(x=> (object)x);
    attr = (TData)Activator.CreateInstance(typeof(TData), typeArguments.Concat(con).ToArray());
}
```

I have no idea why this only happens during the benchmarks and not during the tests or actual use.

**Comment by latonz** [comment] 2023-06-12 13:54
Can you reproduce this on the latest main? I recently changed some things there...

**Comment by latonz** [comment] 2023-06-12 14:06
Sorry I deleted my comment as I understood it could not be fixed by the recent commits on main. Thank you for your analysis, I understand why the issue is coming up. However, I cannot understand, why it doesn't happen on my machine / in my dev environment.

I think the cleanest approach would be to pass the type of the constructor argument or the property through `BuildArgumentValue` to `GetEnumValue`.

**Comment by TimothyMakkison** [comment] 2023-06-12 14:33
> However, I cannot understand, why it doesn't happen on my machine / in my dev environment.

How much memory do your benchmarks use? If it's less that 8000KB then this bug is occuring

> I think the cleanest approach would be to pass the type of the constructor argument or the property through `BuildArgumentValue` to `GetEnumValue`.

What about multiple constructors? I guess it could loop through each one with the same number of arguments

**Comment by TimothyMakkison** [comment] 2023-06-12 16:26
Welp, I have no idea then. I'm still not sure why this is happening. I don't think this affects library users.

It looks like we only need to resolve enums when they are used by Mapperly for configuration. Here I check the symbols namespace only resolving it if it's from `Riok.Mapperly.Abstractions`. 
The logic needs to be changed and there's probably a better namespace check but the following works for me:

```C#
// quick and dirty example
private static object? GetEnumValue(TypedConstant arg)
{
    if (arg.Value == null)
        return null;

    var type = arg.Type ?? throw new InvalidOperationException("Type is null");

    // try to resolve Mapperly enums, otherwise for all other enums find a matching IFieldSymbol
    var enumType = type.ContainingAssembly.Name == "Riok.Mapperly.Abstractions"
        ? GetReflectionType(type)
        : null;

    return enumType == null ? arg.Type.GetFields().First(f => Equals(f.ConstantValue, arg.Value)) : Enum.ToObject(enumType, arg.Value);

```

**Comment by latonz** [comment] 2023-06-13 07:06
Why not pass the type of the target property / constructor argument? IMO this would be the significant information on how to handle values. Could be a boolean whether it should be a roslyn type or a reflection type.

**Comment by TimothyMakkison** [comment] 2023-06-21 16:47
I opted to use a `Create` function to find the constructor parameter types and optionally map with `ToFieldSymbol` or `BuildArgumentValue`. 
Not a massive fan of all these changes to make the benchmarks run. I'd prefer to either use the namespace check or split the benchmark projects so that `SourceGeneratorBenchmarks` doesn't reference the integration tests.

```C#
public IEnumerable<TData> Access<TAttribute, TData>(ISymbol symbol)
    where TAttribute : Attribute
{
    var attrType = typeof(TAttribute);
    var dataType = typeof(TData);
    var attrSymbol = _types.Get($"{attrType.Namespace}.{attrType.Name}");

    var attrDatas = symbol
        .GetAttributes()
        .Where(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass?.ConstructedFrom ?? x.AttributeClass, attrSymbol));

    foreach (var attrData in attrDatas)
    {
        var typeArguments = attrData.AttributeClass?.TypeArguments ?? ImmutableArray<ITypeSymbol>.Empty;
        var attr = Create<TData>(dataType, typeArguments, attrData.ConstructorArguments);

        foreach (var namedArgument in attrData.NamedArguments)
        {
            var prop = dataType.GetProperty(namedArgument.Key);
            if (prop == null)
                throw new InvalidOperationException($"Could not get property {namedArgument.Key} of attribute {attrType.FullName}");

            var argumentValue = prop.PropertyType == typeof(IFieldSymbol)
                ? ToFieldSymbol(namedArgument.Value)
                : BuildArgumentValue(namedArgument.Value);
            prop.SetValue(attr, argumentValue);
        }

        yield return attr;
    }
}

private static TData Create<TData>(Type type, ImmutableArray<ITypeSymbol> typeArguments, ImmutableArray<TypedConstant> arguments)
{
    var argCount = typeArguments.Length + arguments.Length;
    var ctor = type.GetConstructors().First(x => (x.IsGenericMethod ? x.GetGenericArguments().Length : 0) + x.GetParameters().Length == argCount);

    var parameters = ctor.GetParameters();
    var args = new object?[arguments.Length];
    for (var i = 0; i < arguments.Length; i++)
    {
        args[i] = parameters[i].ParameterType == typeof(IFieldSymbol)
            ? ToFieldSymbol(arguments[i])
            : BuildArgumentValue(arguments[i]);
    }

    var newInstanceArguments = typeArguments.Concat(args).ToArray();
    return (TData)Activator.CreateInstance(type, newInstanceArguments);
}

private static IFieldSymbol? ToFieldSymbol(TypedConstant arg) =>
    arg.Type!.GetFields().First(f => Equals(f.ConstantValue, arg.Value));

private static object? BuildArgumentValue(TypedConstant arg)
{
    return arg.Kind switch
    {
        _ when arg.IsNull => null,
        TypedConstantKind.Enum => GetEnumValue(arg),
        TypedConstantKind.Array => BuildArrayValue(arg),
        TypedConstantKind.Primitive => arg.Value,
        TypedConstantKind.Type => arg.Value,
        _
            => throw new ArgumentOutOfRangeException(
                $"{nameof(AttributeDataAccessor)} does not support constructor arguments of kind {arg.Kind.ToString()}"
            ),
    };
}

private static object?[] BuildArrayValue(TypedConstant arg)
{
    var arrayTypeSymbol =
        arg.Type as IArrayTypeSymbol
        ?? throw new InvalidOperationException("Array typed constant is not of type " + nameof(IArrayTypeSymbol));

    var values = arg.Values.Select(BuildArgumentValue).ToArray();

    var elementType = GetReflectionType(arrayTypeSymbol.ElementType);
    if (elementType == null)
        throw new InvalidOperationException("Non reflection array configurations are not supported");

    var typedValues = Array.CreateInstance(elementType, values.Length);
    Array.Copy(values, typedValues, values.Length);
    return (object?[])typedValues;
}

private static object? GetEnumValue(TypedConstant arg)
{
    if (arg.Value == null)
        return null;

    var enumType = GetReflectionType(arg.Type ?? throw new InvalidOperationException("Type is null"));

    // if we can't get the enum type then it's not available to reflection (only accessible by Roslyn) so return the TypedConstant
    // if this is the case, a roslyn typed configuration class should be used which accepts the typed constants.
    return enumType == null ? ToFieldSymbol(arg) : Enum.ToObject(enumType, arg.Value);
}```

**Closed** 2023-06-26 12:55 UTC
Labels: bug
