### ISSUE TITLE
Duplicate source generated mapping methods for collection properties

### ISSUE THREAD

**Issue by MSylar** [riok/mapperly#1075] opened 2024-01-21 15:14 UTC
**Issue description:**

When some classes are using properties of the same collection type, then Mapperly generates the exact same methods to map those collections, with different names.
Note that this issue only occurs, when those collection properties are not nullable.
It is also important to mention that in case I create a private mapper method explicitly in my mapper class to map those lists, then Mapperly properly uses it in the other mapper methods without any issue, and no additional duplicated methods are generated.

**Issue reproduction steps:**

1. Create the source classes:

```csharp
public sealed class SourceA
{
    public string? PropertyA { get; set; }

    public List<SourceC> Cs { get; set; } = new();
}
```

```csharp
public sealed class SourceB
{
    public string? PropertyB { get; set; }

    public List<SourceC> Cs { get; set; } = new();
}
```

```csharp
public sealed class SourceC
{
    public string? PropertyC { get; set; }
}
```
2. Create the destination classes:

```csharp
public sealed class DestinationA
{
    public string? PropertyA { get; set; }

    public List<DestinationC> Cs { get; set; } = new();
}
```

```csharp
public sealed class DestinationB
{
    public string? PropertyB { get; set; }

    public List<DestinationC> Cs { get; set; } = new();
}
```

```csharp
public sealed class DestinationC
{
    public string? PropertyC { get; set; }
}
```

3. Create the mapper methods:

```csharp
[Mapper]
public static partial class MapperClass
{
    public static partial DestinationA MapToDestinationA(this SourceA model);

    public static partial DestinationB MapToDestinationB(this SourceB model);
}
```

4. Check the source generated code:

```csharp
// <auto-generated />
#nullable enable
namespace MapperlyTestProject
{
    public static partial class MapperClass
    {
        public static partial global::MapperlyTestProject.Destinations.DestinationA MapToDestinationA(this global::MapperlyTestProject.Sources.SourceA model)
        {
            var target = new global::MapperlyTestProject.Destinations.DestinationA();
            target.PropertyA = model.PropertyA;
            target.Cs = MapToList(model.Cs);
            return target;
        }

        public static partial global::MapperlyTestProject.Destinations.DestinationB MapToDestinationB(this global::MapperlyTestProject.Sources.SourceB model)
        {
            var target = new global::MapperlyTestProject.Destinations.DestinationB();
            target.PropertyB = model.PropertyB;
            target.Cs = MapToList1(model.Cs);
            return target;
        }

        private static global::MapperlyTestProject.Destinations.DestinationC MapToDestinationC(global::MapperlyTestProject.Sources.SourceC source)
        {
            var target = new global::MapperlyTestProject.Destinations.DestinationC();
            target.PropertyC = source.PropertyC;
            return target;
        }

        private static global::System.Collections.Generic.List<global::MapperlyTestProject.Destinations.DestinationC> MapToList(global::System.Collections.Generic.List<global::MapperlyTestProject.Sources.SourceC> source)
        {
            var target = new global::System.Collections.Generic.List<global::MapperlyTestProject.Destinations.DestinationC>(source.Count);
            foreach (var item in source)
            {
                target.Add(MapToDestinationC(item));
            }
            return target;
        }

        private static global::System.Collections.Generic.List<global::MapperlyTestProject.Destinations.DestinationC> MapToList1(global::System.Collections.Generic.List<global::MapperlyTestProject.Sources.SourceC> source)
        {
            var target = new global::System.Collections.Generic.List<global::MapperlyTestProject.Destinations.DestinationC>(source.Count);
            foreach (var item in source)
            {
                target.Add(MapToDestinationC(item));
            }
            return target;
        }
    }
}
```

**Expected behaviour:**

Mapperly generates only a single private `MapToList` method to map the `List<SourceC>` to `List<DestinationC>`, and it is used in both `MapToDestinationA` and `MapToDestinationB` methods.

**Testing environment:**

Mapperly Version: 3.3.0
Target Framework: .NET 6.0+
IDE: Visual Studio Community 2022, Version 17.8.5
OS: Windows 10

**Comment by TimothyMakkison** [comment] 2024-01-21 16:22
Hey thanks for the bug report. I don't think this is intentional. I've replicated this issue in versions `3.2.0` and `3.1.0`, `3.0.0` doesn't have thie behavious as it uses inline linq methods instead.


> Note that this issue only occurs, when those collection properties are not nullable.

Good catch, Mapperly will also correctly reuse generated `List -> Array` methods. This issue also occurs with `ICollection` and `IList`.

I suspect the code that tries to reuse methods doesn't handle generic types correctly. Not sure why it only an issue for the target type 🤔

**Comment by latonz** [comment] 2024-01-23 17:47
Thanks for opening this issue. I cannot reproduce this with the latest main and the next releases since `3.4.0-next.1`.

I think it got fixed by https://github.com/riok/mapperly/commit/132b8ccc9d1d755415c6f6b17fcab20e286fd77f [EnumerableMappingBuilder:195](https://github.com/riok/mapperly/commit/132b8ccc9d1d755415c6f6b17fcab20e286fd77f#diff-d0e8d4a6f1b4bc7cabf6bf20484b1ff8e57a8fde79753fa4bf2d563df38965dbL195).
I'll investigate more and add tests for this case.

**Comment by latonz** [comment] 2024-01-23 18:02
The problem still exists when one property uses an interface (e.g. `ICollection<X>`) and the other uses another interface/class (e.g. `List<X>`). The generated mapping methods body is the same but with different method signatures. Mapperly currently isn't smart enough to figure out that these two use the same mapping method body and could also use the same signature.

**Closed** 2024-01-26 01:08 UTC
Labels: bug
