### ISSUE TITLE
Clone / Map class hierarchies with non-abstract base class

### ISSUE THREAD

**Issue by danielwinkler** [riok/mapperly#1628] opened 2024-12-05 13:06 UTC
**Is your feature request related to a problem? Please describe.**

I am trying to write a cloner for a class hierarchy with a non-abstract base-class.

```csharp
public class Animal
{
    public required string Name { get; set; }
}

public class Dog : Animal
{
    public required string Breed { get; set; }
}

public class Cat : Animal
{
    public required string Color { get; set; }
}


[Mapper(UseDeepCloning = true)]
public static partial class AnimalCloningExtensions
{
    [MapDerivedType<Dog, Dog>]
    [MapDerivedType<Cat, Cat>]
    [MapDerivedType<Animal, Animal>]
    public static partial Animal MapAnimal(this Animal source);
}
```

The produced code is referencing itself recursively.

```csharp
// <auto-generated />
#nullable enable
namespace Medel.ReDi.WebAPI.Models
{
    public static partial class AnimalCloningExtensions
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        public static partial global::Medel.ReDi.WebAPI.Models.Animal MapAnimal(this global::Medel.ReDi.WebAPI.Models.Animal source)
        {
            return source switch
            {
                global::Medel.ReDi.WebAPI.Models.Dog x => MapToDog(x),
                global::Medel.ReDi.WebAPI.Models.Cat x => MapToCat(x),
                global::Medel.ReDi.WebAPI.Models.Animal x => MapAnimal(x),
                _ => throw new System.ArgumentException($"Cannot map {source.GetType()} to Medel.ReDi.WebAPI.Models.Animal as there is no known derived type mapping", nameof(source)),
            };
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        private static global::Medel.ReDi.WebAPI.Models.Dog MapToDog(global::Medel.ReDi.WebAPI.Models.Dog source)
        {
            var target = new global::Medel.ReDi.WebAPI.Models.Dog()
            {
                Breed = source.Breed,
                Name = source.Name,
            };
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.1.0")]
        private static global::Medel.ReDi.WebAPI.Models.Cat MapToCat(global::Medel.ReDi.WebAPI.Models.Cat source)
        {
            var target = new global::Medel.ReDi.WebAPI.Models.Cat()
            {
                Color = source.Color,
                Name = source.Name,
            };
            return target;
        }
    }
}
```

**Describe the solution you'd like**

It would be great if the base class could also be cloned.

**Comment by latonz** [comment] 2024-12-08 19:43
Duplicate of https://github.com/riok/mapperly/issues/692

**Closed by latonz** 2024-12-08 19:43 UTC
Labels: enhancement
