### ISSUE TITLE
IQueryable doesn't work with non parameterless ctors

### ISSUE THREAD

**Issue by ArkadiuszChorian** [riok/mapperly#972] opened 2023-12-04 09:54 UTC
**Describe the bug**
It's impossible to generate mapping for `IQueryable<T>` when there is a non nullable, non parameterless ctor type in mapped object.
Project with such code has compilation error.
Error in such case is: `Error RMG002 : {SomeType} has no accessible parameterless constructor`.

**To Reproduce**
1. Prepare some value object
`public record ValueObject(string Value);`
2. Prepare entity to map from
```
public class TestEntity
{
    public ValueObject ValueObject { get; set; }
}
```
3. Prepare dto to map to
`public record TestDto(ValueObject ValueObject);`
4. Prepare `IQueryable<T>` mapper
```
[Mapper]
public static partial class TestMapper
{
    public static partial IQueryable<TestDto> SelectDto(this IQueryable<TestEntity> test);
}
```
5. Build

**Expected behavior**
- Build should pass
- `SelectDto` should properly perform mapping when used

**Code snippets**
Generated mapping seems to be fine:
```
    public static partial class TestMapper
    {
        public static partial global::System.Linq.IQueryable<global::Test.TestDto> SelectDto(this global::System.Linq.IQueryable<global::Test.TestEntity> test)
        {
#nullable disable
            return System.Linq.Queryable.Select(test, x => new global::Test.TestDto(x.ValueObject));
#nullable enable
        }
    }
```

**Environment (please complete the following information):**
- Mapperly Version: 3.3.0-next.3
- .NET Version: 8
- Target Framework: net8.0
- IDE: Rider 2023.2.3
- OS: Windows

**Additional context**
I found a workaround for the problem. It works when we make the type in dto nullable.
So instead of this:
`public record TestDto(ValueObject ValueObject);`
Make this:
`public record TestDto(ValueObject? ValueObject);`

I'm very much into DDD and always choose tooling that gives ability to preserve fundamental concepts of DDD.
All above is just example but in real cases I'm implementing I don't want to introduce false statement that something is `nullable` when in real domain it isn't and should be always there.

Also I would appreciate if somebody could explain me why such error ever happen? What internally leads to the necessity of having parameterless ctors on things when the actual generated code even doesn't need this?
There are more issues related with this (see below) and also I wasn't able to generate mappings for common stuff like `IReadOnlyList`, `IReadOnlyDictionary` with same `no accessible parameterless constructor` error but I don't elaborate on this since somehow I believe the reasoning behind could be same for all cases. But still it's strange for me I can't do it for example for list when below you can see similar issue exactly related to list interfaces that has been closed. I want to better understand internals or maybe there is some common factor across these issues that can be fundamentally solved in design?

**Related issues**
- https://github.com/riok/mapperly/issues/247
- https://github.com/riok/mapperly/issues/250

**Comment by latonz** [comment] 2023-12-15 12:58
Closing as no update is received, feel free to reopen...

**Comment by pawel-pajak-espeo** [comment] 2024-02-08 13:55
Here we have a minimal reproduction repo. What is worth noting, removing "ProjectToDto" method makes it all work alright, so the problem must be related to the IQueryable.
Also, worth noting, making the InnerRecord in the DTO nullable, also "fixes" the problem. 
`public record Dto(int Id, InnerRecord? InnerRecord);`

https://github.com/pawel-pajak-espeo/MapperlyNullableProblemMinimalSetup

**Comment by ArkadiuszChorian** [comment] 2024-02-08 14:06
@latonz Can you reopen the issue? @pawel-pajak-espeo cooperates with me regarding this problem because we're working in the same codebase where the problem was discovered.

**Comment by TimothyMakkison** [comment] 2024-02-09 13:25
Thanks for the repo 👍 Looks like the error `InnerRecord has no accessible parameterless constructor.` is produced.

Not entirely sure why this happens, especially when the generated code looks fine, here's my guess:
In `IQueryable` mappings, Mapperly assumes that the source values are potentially nullable. So in our case `Entity.InnerRecord` is assumed to have the type `InnerRecord?`.
As the constructor for `Dto` accepts a non nullable `InnerRecord` Mapperly will attempt to generate the following code to handle the potential null ness of `InnerRecord`.
```C#
return System.Linq.Queryable.Select(form, x => new Dto(x.InnerRecord ?? new InnerRecord()));
```
As `InnerRecord` does not have a parameterless constructor Mapperly settles on passing the potentially null value into the constructor and emits a warning message.

I'm not sure if this is a bug or expected behaviour.

**Comment by ArkadiuszChorian** [comment] 2024-02-12 07:53
@TimothyMakkison that makes sense. For me it seems like bug. How can I reopen this issue?

**Comment by TimothyMakkison** [comment] 2024-02-12 11:43
> @TimothyMakkison that makes sense. For me it seems like bug. 


Yeah, It feels super unintuitive. Not a fan
> How can I reopen this issue?

I think github doesnt allow people to reopen issues. You'll have to wait for @latonz or one of the Riok guys to reopen this.

> There are more issues related with this (see below) and also I wasn't able to generate mappings for common stuff like IReadOnlyList, IReadOnlyDictionary with same no accessible parameterless 

Thanks for mentioning this, it has the same cause but I think it can be fixed. I'll look into adding a special case where `new List<T>` etc is emitted.

**Comment by latonz** [comment] 2024-02-12 14:50
@TimothyMakkison You mention a problem with `List<T>', I couldn't find anything about it. Can you elaborate on what the problem is? If you have the time, I'd also appreciate a review on the PR 😊

**Comment by TimothyMakkison** [comment] 2024-02-12 16:20
> @TimothyMakkison You mention a problem with `List', I couldn't find anything about it. Can you elaborate on what the problem is? If you have the time, 

Iirc something like the following would emit a parameterless constructor error.

```C#
public record Source(List<string> Values);
public record Target(IList<string> Values);

....
public static partial IQueryable<Target>Map(IQueryable<Source> src);
```

It would work fine with `List` as the target as it has an accessible constructor. I suspect #1112 fixes it though.

> I'd also appreciate a review on the PR 😊

Sure! 😊

**Closed** 2024-02-16 09:38 UTC
Labels: bug
