### ISSUE TITLE
Attribute to instruct Mapperly to generate a default value for a target member.

### ISSUE THREAD

**Issue by Phoenix359** [riok/mapperly#749] opened 2023-09-13 10:06 UTC
**Is your feature request related to a problem? Please describe.**

I would like the option to set a default value on the target member when the source cannot provide it.
We now have to constantly make a second mapping function in a separate class just to set a boolean to true  or an int to 1 or ....

```csharp
[Mapper]
public partial class MyMapperlyMapper
{
    [MapperIgnoreTarget(nameof(YourTarget.MonitorProgress))]
    private static partial YourTarget ConvertToYourTarget(Event1 eventMessage);

    [MapperIgnoreTarget(nameof(YourTarget.MonitorProgress))]
    private static partial YourTarget ConvertToYourTarget(Event2 eventMessage);

    [MapperIgnoreTarget(nameof(YourTarget.MonitorProgress))]
    private static partial YourTarget ConvertToYourTarget(Event3 eventMessage);
}
```
```csharp
public static partial class MyMapper
{
    public static YourTarget ToYourTarget(this Event1 eventMessage)
    {
        var yourTarget = ConvertToYourTarget(eventMessage);
        yourTarget.MonitorProgress = true;
        return yourTarget;
    }

    public static YourTarget ToYourTarget(this Event2 eventMessage)
    {
        var yourTarget = ConvertToYourTarget(eventMessage);
        yourTarget.MonitorProgress = false;
        return yourTarget;
    }

    public static YourTarget ToYourTarget(this Event3 eventMessage)
    {
        var yourTarget = ConvertToYourTarget(eventMessage);
        yourTarget.MonitorProgress = true;
        return yourTarget;
    }
}
```

**Describe the solution you'd like**

I would like a new Attribute to instruct Mapperly to generate a default value for a target member.
I would also like to get an compiler warning when this would override a mapping for a source member.

```csharp
[Mapper]
public partial class MyMapperlyMapper
{
    [MapperTargetValue(nameof(YourTarget.MonitorProgress, true))]
    private static partial YourTarget ConvertToYourTarget(Event1 eventMessage);

    [MapperTargetValue(nameof(YourTarget.MonitorProgress, false))]
    private static partial YourTarget ConvertToYourTarget(Event2 eventMessage);

    [MapperTargetValue(nameof(YourTarget.MonitorProgress, true))]
    private static partial YourTarget ConvertToYourTarget(Event3 eventMessage);
}
```

**Describe alternatives you've considered**

I can see use cases were overriding member mappings is desired. That could be implemented with a different attribute or an extra parameter on this one. In that case i expect no compiler warning, because this explicitly instructs mapperly to override the source.

```csharp
[MapperOverrideSourceValue(nameof(YourTarget.MonitorProgress, true))]

[MapperTargetValue(nameof(YourTarget.MonitorProgress, true, overrideSource: true))]
```

**Additional context**
-

**Comment by latonz** [comment] 2023-09-13 11:03
Closing as duplicate of https://github.com/riok/mapperly/issues/631

**Closed by latonz** 2023-09-13 11:03 UTC
