### ISSUE TITLE
Documentation for MappingConversionType is broken

### ISSUE THREAD

**Issue by JKetelaar** [riok/mapperly#314] opened 2023-04-06 15:53 UTC
**Describe the bug**
The documentation page for MappingConversionType is broken. 
See: https://mapperly.riok.app/docs/api/riok.mapperly.abstractions.mappingconversiontype

Possibly due to the code using [`<see cref="string"/>`](https://github.com/riok/mapperly/blob/ad35feb5d74f59a2510204be3200fdcdcd96de85/src/Riok.Mapperly.Abstractions/MappingConversionType.cs#L32)

**Comment by latonz** [comment] 2023-04-10 08:31
To generate the c# xml docs based markdown api description [xmldoc2md](https://github.com/charlesdevandiere/xmldoc2md) is used. This is an issue in xmldoc2md: https://github.com/charlesdevandiere/xmldoc2md/issues/23 triggered by the NL's in the summary of the xml doc. The bug should be fixed there. However, I'm not sure if xmldoc2md is still maintained, therefore we should probably consider alternative tools to generate the markdown based on the c# xml docs.

**Comment by TimothyMakkison** [comment] 2023-05-03 21:20
This should be fixed in the latest version of `xmldoc2md` [see](https://github.com/charlesdevandiere/xmldoc2md/pull/25).

**Comment by latonz** [comment] 2023-05-04 05:45
Created a PR to upgrade all dotnet-tools as they don't seem to be picked up by dependabot.

**Closed** 2023-05-04 08:56 UTC
Labels: documentation

**Comment by TimothyMakkison** [comment] 2023-05-27 21:49
This still appears to be broken. Is this still caused by xml2doc? I tested my changes with `MappingConversionType` and it seemed to work.

**Comment by latonz** [comment] 2023-05-30 16:11
@TimothyMakkison the fix is deployed on the next docs: https://next.mapperly.pages.dev/docs/api/riok.mapperly.abstractions.mappingconversiontype. Documentation releases are only automatically published when a new Mapperly release is published. As new features are already added to the documentation, triggering the deployment manually would need a new branch and cherry picking the commits to deploy, therefore I think waiting for the upcoming stable release should be fine.

**Comment by TimothyMakkison** [comment] 2023-05-30 16:14
Thanks, thought this might be the case. Happy to see my fix worked!
