### ISSUE TITLE
Map properties based on other property (gRPC)

### ISSUE THREAD

**Issue by pfeigl** [riok/mapperly#1012] opened 2023-12-15 16:46 UTC
**Is your feature request related to a problem? Please describe.**
We are using Mapperly to map between hand-crafted objects and objects auto-generated from .proto files.
These auto-generated classes have one very special handling:
When a property is defined `optional` in the proto file, the C# property is actually not nullable (as we would have expected) but generates a `HasX` property. 
Example:
```proto
message MyObject {
    optional string Name;
}
```
generates roughly this class
```csharp
class MyObject
{
    public string name_;
    public string Name 
    { 
        get => name_ ?? "";
        set => _name = value ?? throw new ArgumentNullException(nameof(Name));
    }
    public bool HasName => _name != null;    
}
```
So from the generated classes view, the public property ALWAYS has a value (in this case empty string, but the same concepts apply to things like `int? double?` and so on.

Now, where does this get me to:
If we were to simply let Mapperly generate the mappings, we would end up in a situation, where the initial null value is a empty string in the target object.
In earlier versions of mapperly we even saw the Exceptions in the generated proto C# code, but this was fixable through `AllowNullPropertyAssignment = false` (thanks for that btw).

**Describe the solution you'd like**
See next point, I'm honestly not sure about what solution I'd like. Really open to discussion here.

**Describe alternatives you've considered**
* One option would be, that Mapperly "somehow" allows to reflect this logic like "if there is a `HasX` property for the property `X` and it returns `bool`, we check that. Would absolutely solve our usecase, but I do understand, that mapperly probably should / can not support specifics from other code generated codes (on the other hand, the gRPC implementation might be big enough to still consider it?)
* Can we somehow emit custom code into the source generation? That would possibly allow us to implement this special logic ourself or even provide it as a integration nuget package between mapperly and gRPC for .NET
* We understand that we can solve the problem by using https://mapperly.riok.app/docs/configuration/before-after-map/, but this would force us to implement a custom method for almost 90% of the classes and change 100's of properties after the initial mapping.
Also this feels very error-prone, as new properties might be added to the proto files and ppl miss to add them in the after map code.

**Additional context**
* We would have loved to never have this problem and for the gRPC implementation to simply generate nullable properties for `optional` fields. There was quite some discussion on that matter over here https://github.com/protocolbuffers/protobuf/issues/9083 but it was eventually closed as the breaking changes can not be considered anymore.
* We are aware that google offers proto Wrappers like `StringValue` or `Int32Value` which actually generate nullabe properties in C#. While this would solve the problem, it comes with two other problems
  * The proto files must be considered as is
  * Even if we could modify the proto files, not using the language defaults just because the code generation is not as we want it seems to be very bad practice.

So as said already, we are not sure what the best solution would. Very open to ideas and discussion!

Thanks,
Philipp

**Comment by latonz** [comment] 2023-12-17 16:02
I completely understand your problem. We have already discussed whether Mapperly should provide a way to fix wrong or missing nullable annotations in 3rd party code in other issues / discussions, IMO the same applies here.
* To keep the Mapperly implementation maintainable, it needs to focus on its main goals. Fixing the interpretation of wrong/missing nullable annotations or alternative semantics for expressing nullability is not one of Mapperly's tasks. Mapperly implements the handling of nullability using the standard C# nullable annotations.
* Supporting `Has*` and `Clear*` would add a lot of complexity to Mapperly just to support one specific use case (namely protoc-generated source code, I don't know of any other library that uses `Has*` and `Clear*` notation for nullable properties). We try to keep the Mapperly implementation maintainable by focusing on its main goals.
* AFAIK injecting custom code into the source generator at compile time is not possible in an efficient and reliable way with good DX. Let me know if you know of a way to achieve injecting custom code into a source generator while maintaining great performance and a nice DX 😊.

**Comment by pfeigl** [comment] 2023-12-18 11:00
I feared a little that no real solution will be available, tough I can understand it.

> I don't know of any other library that uses Has* and Clear* notation for nullable properties).
Microsoft is (*was) doing similar stuff in different areas, i.e. XmlSerialization with the `*Specified` notation or the `ShouldSerialize*` and `Reset*` notation like here https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls-design/how-to-designer-properties-shouldserialize-reset?view=netdesktop-8.0

In the end we might end up doing some (cached) reflection stuff for now in after maps

**Comment by latonz** [comment] 2023-12-18 12:38
The problem is that before nullable reference types, there was no standard notation for how to handle this scenario. So there are a lot of different notations (you just made me aware of three; protoc, xml, WinForms, but I think there might be more). This would make the Mapperly implementation complex, while still not being able to support all scenarios.

I'm aware that the situation is far from optimal, but IMO the way to improve it is to adapt the nullable reference types in the libraries & code generators in question.

I'll close this for now, as we currently have no plans to improve the situation on Mapperly's end. We may revisit this if there is a lot of demand for it.

**Closed by latonz** 2023-12-18 12:38 UTC
