### ISSUE TITLE
Supply additional parameters to the mapping method

### ISSUE THREAD

**Issue by cyril265** [riok/mapperly#103] opened 2022-07-18 19:01 UTC
Sometimes you want to provide an external value to the mapping method. For example your DTO doesn't have a tenant id. You are getting the tenant id from the currently signed in user and it's the same for every entity inside the current request.

```c#
[Mapper]
public partial class CarMapper
{
    public partial Car Map(CarDto dto, string tenantId);
}

public record Car(string Name, string TenantId);

public record CarDto(string Name);

```
Example usage:

```C#
    public void UseMapper(CarMapper mapper, IEnumerable<CarDto> dtos)
    {
        string tenantId = ""; //GetFromDb;
        var entities = dtos.Select(dto => mapper.Map(dto, tenantId));
    }
```
You could accomplish this by moving `TenantId` to a property and using the after map feature. But I think this solution is cleaner. It doesn't force you to change your domain code for a mapper, it shows the intent more clearly and it's simpler to add.

**Comment by latonz** [comment] 2022-07-19 09:05
I like this idea. However, it is not that easy to implement. It may take some time until Mapperly supports this.

**Comment by latonz** [comment] 2022-12-12 11:06
@Fube Sorry, I missed the notification of your comment.
I didn't have the time to think about a concrete architecture yet. Are all arguments considered as mapping sources? Or are the additional arguments only sources for properties with the same name? On a first glance I think if all arguments are considered as mapping sources, the `TypeMapping` needs to be refactored. Otherwise it seems to be limited to the `PropertyMapping` and it's related classes. Tbd is also how to handle it, if another mapping depends on a user defined mapping with additional arguments. 

Feel free to submit an architectural proposal to this issue.

**Comment by DerMave** [comment] 2022-12-25 08:56
I would like to work on this feature as I have an usecase for it. Have you begun working on this? @latonz @Fube

**Comment by Fube** [comment] 2022-12-25 15:26
@DerMave 
Unfortunately not, but feel free to takeover.
I investigated the issue, but did not have time to come up with a solution.

As far as I can tell, the `TypeMapping` has to be changed to account for more than one source.

**Comment by latonz** [comment] 2023-01-02 07:06
@DerMave I didn't have time yet to work on this. Let me know if you start working on this, then I'd assign the issue to you.
However, before you start with an actual implementation, I think it would be useful to discuss a design proposal on how this feature should work exactly and which parts of Mapperly need adjustments.

**Comment by akoken** [comment] 2023-01-07 14:27
+1 for this feature. I think this is very common use case. As @cyril265 mentioned above, we also obtain tenantId, userId etc. from HttpContext.

**Comment by DerMave** [comment] 2023-01-10 12:29
@latonz I haven't really gotten around to it yet. I made some unit tests and looked at the relevant bits and pieces. It seems I have underestimated the scope of this change. I am still interested in going forward with it, but I have to find some free time.

**Comment by Fube** [comment] 2023-03-18 21:55
Maybe we can use the flattening / unflattening logic to implement this
We could make an intermediary type to nest the arguments and then flatten it into the target type

Though it is a bit hacky, if it is possible, it would be the simplest way to implement this

Otherwise, we're looking at a change in `IMapping` which would propagate throughout the rest of the code

Not sure if my suggestion makes sense though, @latonz is it plausible?

**Comment by latonz** [comment] 2023-03-29 08:47
@Fube I don't think flattening/unflattening would be the right approach for this, it could work as a workaround though.
IMO the way to go would either be providing parameters directly to the mapping methods which are then mapped by name to properties of the target object or to add a secondary source objects which are also considered as mapping sources.

**Comment by Herdo** [comment] 2023-05-19 12:29
This is currently the blocking issue for me to switch from AutoMapper to Mapperly.

I'm receiving requests that are mapped to an internal command and require additional properties from the HttpContext.

**Comment by TimothyMakkison** [comment] 2023-06-22 18:43
I have a working POC for this feature, I've opted to change `IMapping` and add `MethodParameter[] Parameters { get; }` (probably shouldn't be using `MethodParameter`)

I have some questions/concerns about breaking future features.

- How should method resolving work?
  - For void method mappings should the target member always be the second  non type/IRefernceHandler parameter
  - Derived type mapping uses `Type` as a discriminator, unlike `IReferenceHandler` it doesn't use an attribute label. Could this cause issues while parsing the method?
  - Might cause future issues with #276 
- Where are additional parameter mappings allowed?
  - Stay in the first method scope
  - Pass all the parameters to all methods where possible
  - Used in methods when needed (possible but hard)
- Should multi param user implemented mapping be allowed. How should the resolution be handled? ie match by type and name. 
   - When trying to use a user mapping should Mapperly attempt to resolve the parameters by finding matching members? ie `ToDogDto(src.Dog, src.DogOwner, id)`
- I'm currently using the name of the variable to determine if it can map to a member. This feels natural but is a bit of an anti pattern, plus Mapperly doesn't do this for the source type.

**Comment by Herdo** [comment] 2023-06-23 07:17
@TimothyMakkison I think most of the listed questions derive from the fact that you approach it in an implicit way.

Wouldn't most of these questions vanish if we followed an explicit approach by introducing an additional attribute:

```cs
[MapAdditionalValueToProperty("id", "ChipId")]
public partial DogDto MapDogToDto(Dog dog, Guid id);
```

Attribute name could be whatever, though.

**Comment by TimothyMakkison** [comment] 2023-06-23 10:05
@Herdo you're right most of my problems are self inflicted 😄 
I almost mentioned an explicit attribute but decided to try implementing implicit parameters first. It feels much more idiomatic.

**Comment by TimothyMakkison** [comment] 2023-07-08 15:24
I have two ideas for this feature and am not sure which one would be better.

## Top Level
- Additional parameters are only used on the immediate mapping, generated `NewInstanceObjectMemberMapping` will not pass parameters down.
```C#
// This works
public partial DogDto ToDogDto(Dog src, int id)
{
    return new DogDto(src.Name, id);
}

public partial CatOwnerDto ToCatOwnerDto(CatOwner src, int id)
{
    var target = new CatOwnerDto()
    {
        // id will not be passed
        Cat = MapToCatDto(src.Cat);
    }
    return target;
}
```
- If a user defined or user implemented method is found with similar parameters it will be used.
```C#
// User defined mapping (can also be user implemented)
public partial CatDto ToCatDto(Cat src, int id) ...
// public CatDto ToCatDto(Cat src, int id) ...

public partial CatOwnerDto ToCatOwnerDto(CatOwner src, int id)
{
    var target = new CatOwnerDto()
    {
        // id will be passed
        Cat = ToCatDto(src.Cat, id);
    }
    return target;
}
```

### Pros
- Faster to generate
- Simple
- Top level is similar to other mapperly features

### Cons
- Cumbersome
  - Using an extra parameter for a nested property forces you to add a user defined mappings for each step
     - Could use `[MapProperty]` (won't work with init/required)

## Nested
- Additional parameters can be used for all levels of the mapping.
   - The mapper is smart enough to determine if a new method needs an extra parameter, even if a child of the new method uses it. (Its also recursion safe)
- Methods created by the mapping that use extra parameters are scoped to the current user defined mapping to avoid resolving/config issues.
- Can use other user implemented or user  defined methods.

```C#
public partial CatOwnerDto ToCatOwnerDto(CatOwner src, int id)
{
    var target = new CatOwnerDto()
    {
        // below method was created by Mapperly, no user defined method required
        // if the method doesn't need `id`, it would not be passed
        Cat = MapToCatDto(src.Cat, id);
    }
    return target;
}
```

### Pros
- Easier to use
- In the future logic can be adapted to support nested ignores and nested init/required mapping and more.
- Works with nested init/required

### Cons
- Slower generation
- Potentially confusing
- Will likely require nested mapping and nested ignores to be added



I have a working POC for the nested logic mapper see #550. It can be adapted to do top level mappings

**Comment by latonz** [comment] 2023-07-12 08:14
I'm busy right now and I'm afraid I won't find time in the upcoming days to look into this 😞, but I'll look into it in the upcoming weeks. In the meantime I'd like to focus on getting [v2.9.0](https://github.com/riok/mapperly/milestone/1) released 😊

**Comment by MisinformedDNA** [comment] 2023-07-28 17:13
Ideally, this would work without any additional attributes or modifications:

```cs
public record Person(string FirstName, string LastName);
public record Employee(string FirstName, string LastName, string EmployeeId);

public static partial Employee ToEmployee(this Person person, string EmployeeId);
```

**Workaround**

```cs
public record Employee(string FirstName, string LastName, string EmployeeId)
{
    public string EmployeeId { get; init; } = default!;
}

public static Employee ToEmployee(this Person person, string employeeId)
{
    return person.ToEmployee() with { EmployeeId = EmployeeId };
}

[MapperIgnoreSource(nameof(Employee.EmployeeId))]
private static partial Employee ToEmployee(this Person person);
```

**Comment by MisinformedDNA** [comment] 2023-09-09 18:47
> This sounds like a terrible idea to do using AutoMapper or Mapperly. Writing a few manual mappings for complex situations seems like more maintainable for the codebase and for this library.

That's the same argument against Mapperly and AutoMapper in general. Whether it is terrible is subjective and developers can choose to use it or not.

**Comment by darlov** [comment] 2023-11-14 09:32
From my perspective every parameters should have the attribute to identify the destination property for assign to. It's will avoid mistakes when properties will renamed and it's add ability to rename all mappings without manual work for rename every parameters.
Look's like this:
```csharp
[Mapper]
public partial class CarMapper
{
    public partial Car Map(CarDto dto, [MapTo(nameof(Car.TenantId))] string tenantId);
}

[AttributeUsage(AttributeTargets.Parameter)]
public sealed class MapTo : Attribute
{
  public MapTo(string name)
  {
    Name = name;
  }
  
  public string Name { get; }
}
```

**Comment by latonz** [comment] 2024-03-15 20:00
No updates, feel free to contribute.

I think before an implementation, several things need to be thought of and decided:
* Are mapping methods with additional parameters still resolved by Mapperly in transitive mappings? 
* Are only explicitly mapped parameters allowed (`MapTo` (https://github.com/riok/mapperly/issues/103#issuecomment-1809849278) approach)?
* If not only explicitly mapped parameters are allowed, are the parameters handled the same as the source object (eg. only properties of the additional parameters are considered) or are they handled the same as a source object property?

I think handling these mappings the same as the generic mappings (they are never called by Mapperly generated code) with an explicitly mapped parameter (`MapTo`) approach would be the best for now. The added complexity is manageable while still addressing most of the use-cases. This would only allow additional parameters to be mapped to the target object directly.

**Comment by ChaseFlorell** [comment] 2024-03-25 22:23
As far as (2) is concerned, what happens if the target object only has a ctor parameter and no public facing property? I feel as though we can _have_ the opinion within our codebase without forcing the opinion globally. I for one only use ctor mapping and forcing the MapTo would give me heartburn.

**Comment by latonz** [comment] 2024-03-25 22:24
You could simply provide the name of the ctor parameter to MapTo.

**Comment by ChaseFlorell** [comment] 2024-03-25 22:29
> You could simply provide the name of the ctor parameter to MapTo.

doesn't that defeat the `nameof` and the rationale given by @darlov around renaming properties?

**Comment by latonz** [comment] 2024-03-25 22:35
Nameof: yes it does
There is no real technical reason in Mapperly to require this, it just clearifies things on the user side. Otherwise the question would arise whether a parameter object is considered the same as a property on the source object or as an other source object itself.

**Comment by ChaseFlorell** [comment] 2024-03-25 22:37
I think the thing I love about this library is that we get compile time errors when mappings fail. It makes it crystal clear to the developer why a mapping is no bueno. Don't get me wrong, I love the option to add a `[MapTo]` attribute for additional flexibility, I'm only cautioning against forcing it.

**Comment by latonz** [comment] 2024-03-25 22:40
@ChaseFlorell which option would you prefer and why? Matching the the additional parameter itself to a target property or matching the additional parameter's properties to target properties?

**Comment by ChaseFlorell** [comment] 2024-03-25 22:44
I'm not sure I follow the question.
I want to match additional parameters to constructor parameters because there are no target properties to match. I understand that there are scenarios where there _are_ properties, but my use case doesn't have it.

I am new to the world of source generation so I'm ignorant to some of it. Can you match to types and/or case insensitive name?

```csharp
public partial Car ToCar(CarDto car, ICarContext carContext);
// matches
public Car ( /*car properties*/, ICarContext carContext) // matches by name
```

or

```csharp
public partial Car ToCar(CarDto car, ICarContext carContext);
// matches
public Car ( /*car properties*/, ICarContext ctx) // matches by type
```

**Comment by ChaseFlorell** [comment] 2024-03-26 14:35
> @ChaseFlorell which option would you prefer and why? Matching the the additional parameter itself to a target property or matching the additional parameter's properties to target properties?

Oh wait, I think I understand the question now.

I think the first parameter should be the mapped object source => target.
I think any additional parameters should always match to the type on the target. In other words, I don't think additional parameters in a mapping method should even consider additional mapping, it should always be a 1:1 type with the target. I say this because if there are any additional items that need mapping, they should be done as a part of the source => target mapping OR can be done before the mapping call.

**Comment by ChaseFlorell** [comment] 2024-03-26 15:58
> What if matching by type is not enough? For example, would the following work?
I think that's where matching by name would come in. If it were me, I think I'd go something like this

3. Try matching by `[MapTo]`
2. Try matching by type (faster than name because we don't have to worry about case)
1. Try matching by name
4. throw

**Comment by latonz** [comment] 2024-03-27 16:20
Matching by type would again be a completely different approach which Mapperly currently doesn‘t have any support for at all.

**Comment by ChaseFlorell** [comment] 2024-03-27 17:41
> Matching by type would again be a completely different approach which Mapperly currently doesn‘t have any support for at all.

Is it something Mapperly _could_ support? Is there an openness for this?

**Comment by latonz** [comment] 2024-03-28 16:41
Mapperly could support it, but I don‘t see why it would be useful. A common use-case I see for this feature is if you have an entity you want to map with additional data (for example from headers/metadata/…). Often the data from the headers is not in the same format / classes as the data on your business layer.

**Comment by robinabganpat** [comment] 2024-04-12 09:29
> Mapperly could support it, but I don‘t see why it would be useful. A common use-case I see for this feature is if you have an entity you want to map with additional data (for example from headers/metadata/…). Often the data from the headers is not in the same format / classes as the data on your business layer.

You mention you don't see why it would be useful, but then mention a use case where it would be useful... 😂 

Another use case I would see this fit, is when you want to map from a parent-child business layer model to a data layer model. In the business layer you'd probably need only need certain properties (like an ID) at the top level model and not in any child models, but in the data layer, you'd need those properties for all your child models to be able to save the relation between the parent and the child model.

**Comment by DDaveid** [comment] 2024-04-13 16:44
The fastest solution to use this would be to use **[UserMapping]** attribute with as many properties as you like.
```cs
public record CarDto(string Name, long Number);
public record Car(string Name);

[MapperIgnoreTarget(nameof(Car.Number))]
private partial CarDto MapToCarDtoPrivate(Car source)

[UserMapping]
public CarDto MapToCarDto(Car source, long number)
{
    var dto = this.MapToCarDtoPrivate(source);
    dto.Number = number;
    return dto;
}
```
the problem is however, that even if I use [UserMapping] attribute, the compiler does not allow me to add more properties into the User Defined mapping.
**RMG001: MapToCarDto has an unsupported mapping method signature.**
Would it be possible to disable this error for UserDefined mappings?

**Comment by DDaveid** [comment] 2024-04-13 17:43
@latonz I thought the [UserMapping] attribute had to be set for all "User implemented mappings", nevermind that. 
If I just use the function without the Attribute, I can use it from outside and I am OK that mapperly does not pick it up, because it is a top-level mapping.
So basically until the multi-parameter feat is not supported, I am using it like above.
1. set a public function with multiple parameters that I am calling from Controllers, Services, etc.
2. set a private function with 1 parameter that I am calling from the public one.
3. map the additional parameters in the public function **manually**, the rest is handled by the private autogenerated one.

just like the code above, but without the [UserMapping] attribute there.

**Comment by bberka** [comment] 2024-05-23 15:00
This was something i had a use case for simply converting some entities to Log version of that entity and i found this workaround for it. Might not be the best thing but simplest way to do it is this for now.

```csharp
[Mapper]
public static partial class MapperProductInformation
{
  [MapperIgnoreSource(nameof(ProductInformation.Id))]
  private static partial ProductInformationLog ToLogEntityInternal(this ProductInformation product);
  public static ProductInformationLog ToLogEntity(this ProductInformation product, ProductInformationLogType type) {
    var entity = ToLogEntityInternal(product);
    entity.Id = Guid.NewGuid(); //could remove this and let EF handle it
    entity.Type = type;
    return entity;
  }
}
```

This way i make sure ProductInformationLogType is always passed when mapping to log entity.

**Comment by cremor** [comment] 2024-05-23 16:34
> I like that newer .NET languages allow for the `init` keyword in order to make it immutable

The shown code wouldn't compile if the `Type` property had an `init` setter. A real solution with Mapperly support is needed.

**Comment by ChaseFlorell** [comment] 2024-05-23 16:35
> > I like that newer .NET languages allow for the `init` keyword in order to make it immutable
> 
> The shown code wouldn't compile if the `Type` property had an `init` setter. A real solution with Mapperly support is needed.

aaaah, good point. That didn't even dawn on me.

**Comment by bberka** [comment] 2024-05-23 20:08
> > I like that newer .NET languages allow for the `init` keyword in order to make it immutable
> 
> The shown code wouldn't compile if the `Type` property had an `init` setter. A real solution with Mapperly support is needed.

Yes only downside would be you have to set setter public in order to use this. All tho you can make the mapper method take created instance but then you either need to choose between model properties or the parameters for the constructor to take.

I agree with you tho library should implement something like this.

I would also like to see custom mapper methods for the properties to take the original parameter best way would be using attributes to specify it is from parameters or properties etc. Something like this:

```csharp
  public static partial ProductInformationLog ToLogEntity(this ProductInformation e,int errorLevel);

  private static string MapLevel([Parameter] int level) {
    if(level == 0)
       return "success";
    return "fail";
  }
```

**Closed** 2024-07-26 04:42 UTC
Labels: enhancement
