### ISSUE TITLE
Build errors using Mapperly with EntityFramework

### ISSUE THREAD

**Issue by cloudlene** [riok/mapperly#377] opened 2023-04-26 01:59 UTC
I use VS.Net 2022 and I have a .Models C# Class Library project that references an .Entities C# Class Library project. Both reference EntityFrameworkCore assemblies.

```
    [Mapper]
    public partial class ProgramMapper
    {
        public partial Entities.Program Map(Program program);
        public partial Program Map(Entities.Program program);
        public partial void Map(Entities.Program entity, Program model);
        public partial void Map(Program model, Entities.Program entity);
    }
```

I receive 4 errors stating that Partial method 'xxx' must have an implementation part because it has accessibility modifiers.  These are straight up build errors and can't proceed.  What am I doing wrong?

I see the code generated ProgramMapper.g.cs under the Riok.Mapperly.MapperGenerator under the Riok.Mapperly analyzer.

IDE: VS2022 on Windows 11
C# 11
.Net 7

**Comment by latonz** [comment] 2023-04-26 05:17
Closing as duplicate of https://github.com/riok/mapperly/discussions/374

**Closed by latonz** 2023-04-26 05:17 UTC
