### ISSUE TITLE
Multiple conversions for property pairs of the same type

### ISSUE THREAD

**Issue by ialexj** [riok/mapperly#886] opened 2023-11-10 13:04 UTC
I apologize in advance if this is already possible or already requested, I couldn't find anything using the search.

I seem to be unable to specify different conversions for two properties of the same types. Consider the following situation:

```csharp
class Model
{  
    public DateTime Date { get; set; }
    public DateTime Time { get; set; }
}

class Dto
{
    public string Date { get; set; }
    public string Time { get; set; }
}

[Mapper]
static partial class Mapper
{
    public static partial Dto ToDto(this Model model); // always uses first

    static string ToDate(DateTime date) => date.ToShortDateString();
    static string ToTime(DateTime time) => time.ToShortTimeString();
}
```

**Describe the solution you'd like**
The `MapProperty` attribute should be augmented to allow the programmer to manually specify the conversion:
```csharp
[Mapper]
static partial class Mapper
{
    [MapProperty(nameof(Model.Date), nameof(Dto.Date), Method = nameof(ToDate)]
    [MapProperty(nameof(Model.Time), nameof(Dto.Time), Method = nameof(ToTime)]
    public static partial Dto ToDto(this Model date);

    static string ToDate(DateTime date) => date.ToShortDateString();
    static string ToTime(DateTime time) => time.ToShortTimeString();
}
```
It should also support external mappers, so:
```csharp
[Mapper]
[UseStaticMapper(typeof(DateTimeMapper))] // maybe not necessary if specified in MapProperty?
static partial class DateModelMapper
{
    [MapProperty(nameof(Model.Date), nameof(Dto.Date), Mapper = typeof(DateTimeMapper), Method = nameof(DateTimeMapper.ToDate))]
    [MapProperty(nameof(Model.Time), nameof(Dto.Time), Mapper = typeof(DateTimeMapper), Method = nameof(DateTimeMapper.ToTime))]
    public static partial Dto ToDto(this Model date);
}

static class DateTimeMapper
{
    public static string ToDate(DateTime date) => date.ToShortDateString();
    public static string ToTime(DateTime time) => time.ToShortTimeString();
}
```
**Describe alternatives you've considered**
This can be solved by setting those properties after the fact, but it's not elegant.
The most common use case for me would be custom string formatting, so just options to specify the formatting would go a long way. I will post that as a separate issue.

**Additional context**
This should not be a breaking change, as multiple mapping methods with the same types aren't even supported right now. Depending on how the code is written, allowing for them may be a challenge. 

Right now this is the only issue that's keeping me from moving from Automapper to Mapperly on several big projects.

**Comment by latonz** [comment] 2023-11-13 05:06
This seems to be a duplicate of https://github.com/riok/mapperly/issues/783 (adding `UseMethod` to `MapPropertyAttribute`). I'll extend the design of #783 to include the ability to use other mapping methods.

**Closed by latonz** 2023-11-13 05:06 UTC
