### ISSUE TITLE
CI pipeline fails with IDE0060 messages

### ISSUE THREAD

**Issue by TubaMirabilis** [riok/mapperly#1571] opened 2024-10-31 21:48 UTC
I used Visual Studio to update to Mapperly 4.1.0 earlier today.

I did not realize that anything was wrong until GitHub Actions sent me an email saying that our batch of tests which check formatting using tools such as 'dotnet format' and 'prettier' had failed.

When running 'dotnet format --verify-no-changes' the check fails due to mapper classes affected by the IDE0060 diagnostic "Remove unused parameter if it is not part
of a shipped public API"

The expected behavior is that 'dotnet format --verify-no-changes' will exit with code 0 as long as there are no formatting problems.

The actual behavior is that 'dotnet format --verify-no-changes' is exiting with a non-zero code and GitHub Actions' runner is failing our push and pull request checks.

I am bypassing the problem by running 'dotnet format --verify-no-changes --exclude-diagnostics IDE0060' for now.

- Mapperly Version: 4.1.0
- Nullable reference types: Enabled
- .NET Version: 8.0.402
- Target Framework: net8.0
- C# Language Version: 12.0
- IDE: n/a
- OS: n/a

**Comment by latonz** [comment] 2024-11-01 08:47
Could you provide some code samples?

**Comment by TubaMirabilis** [comment] 2024-11-01 08:53
[Mapper]
public sealed partial class DeviceMapper
{
    [MapProperty("Name.Value", "Name")]
    public static partial DeviceDto MapDeviceToDeviceDto(Device d);
}

It seems that the annalyzer is complaining that the input d is never used to form an output, but it doesn't understand that this is a partial method.

**Comment by latonz** [comment] 2024-11-01 09:03
Please format the code with github markdown. Is the parameter used in the generated code?

**Comment by TubaMirabilis** [comment] 2024-11-01 09:16
Generated code:

```csharp
// <auto-generated />
#nullable enable
namespace MyProject.Api.Common.Mapping
{
    public static partial class DeviceMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.1.0.0")]
        public static partial global::Shared.Contracts.DeviceDto MapDeviceToDeviceDto(global::MyProject.Api.Common.Domain.UserData.Devices.Device d)
        {
            var target = new global::Shared.Contracts.DeviceDto(d.Id, d.Name.Value);
            return target;
        }
    }
}
```

**Comment by latonz** [comment] 2024-11-01 09:20
Looks like this is a problem of the analyzer and cannot be fixed within Mapperly... You may need to open an issue in the repo of the analyzer to get this fixed.

**Closed by latonz** 2024-11-01 09:20 UTC
Labels: bug

**Comment by ArmandRedgate** [comment] 2024-11-01 17:35
I can confirm we're getting the same problem since 4.1.0. Not sure what changed between now and the last release for the analyser to be no longer happy.

**Comment by ArmandRedgate** [comment] 2024-11-01 17:51
There are two solutions for consumers of Mapperly as far as I can tell

1) Build your project before running `dotnet format` so the Mapperly file is generated.
2) ignore the `IDE0060` rule for just the Mapperly file

The former could be quite expensive in CI.

Instead, I recommend the latter. It can be done by adding the following to your editor config:

```editorconfig
[*ModelMapper.cs]
dotnet_diagnostic.IDE0060.severity = none
```

Where `ModelMapper` can be replaced with the name of your Mapperly file. I believe you can specify more complex patterns if you have multiple files.

**Comment by jakoss** [comment] 2024-11-20 13:27
Related issue: https://github.com/dotnet/roslyn/issues/75700 - if somebody is interested in tracking that
