### ISSUE TITLE
Mapperly does not work on .NET Framework 4.x.

### ISSUE THREAD

**Issue by randarp** [riok/mapperly#1087] opened 2024-01-23 23:59 UTC
See https://mapperly.riok.app/docs/intro/#requirements

It says that it works on .NET Framework 4.x., but also says that it requires C# language version 9 or later. The problem is, C# version 9 is not available on .NET Framework 4.x. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults. You can't have the required partial methods without v9.

Somebody on my team proved this by creating a standalone .Net 4.8 application and trying to get Mapperly to compile. Even tried to hardcode the language to 9 by editing the project file directly. The same code worked on .Net 5.

I think you need to change requirements from 4.x to 5.x

**Comment by TimothyMakkison** [comment] 2024-01-24 00:16
Hey, while your link states that .NET framework uses the language version 7.3 by default, it is possible and very common to use more recent version of the C# with older versions of .NET. 

Simply go to your csproj file and add `<LangVersion>12.0</LangVersion>` to use C# 12

**Comment by TimothyMakkison** [comment] 2024-01-24 00:47
Hey, sorry to hear about that. Mapperly should definitely work with .NET Framework as it's part of the integration tests. You will need to manually set the `LangVersion` to something greater than or equal to C# 9.0. Try restarting your ide and rebuilding.

>Somebody on my team proved this by creating a standalone .Net 4.8 application and trying to get Mapperly to compile. Even tried to hardcode the language to 9 by editing the project file directly. The same code worked on .Net 5.

I created a new .NET 8 project, manually downgraded to .NET 4.8 and set the langversion and it was able to build. Perhaps projects that are originally .NET Framework are different

**Comment by julianpetriv** [comment] 2024-01-24 00:51
I also confirm that newly created .NET Framework 4.7.2 project won't build with CS8795 error "partial method must have an implementation part because it has accessibility modifiers"

**Comment by latonz** [comment] 2024-01-25 07:03
I cant reproduce either...
If you add `#error version` in a `.cs` file in your solution and build it, what does the output error show?
Could you push a minimal reproducible in a GitHub repository and add the link here?

**Comment by julianpetriv** [comment] 2024-01-25 10:42
#error version shows this: "Compiler version: '4.8.0-7.23572.1 (7b75981c)'. Language version: 9.0."

Here's the reproducible example: https://github.com/julianpetriv/TestMapperlyNetFramework (be aware that for some reason VS doesn't want to find Riot package on freshly cloned project, but unloading and reloading the project helps).

Thanks in advance!

**Comment by caesay** [comment] 2024-01-26 10:12
@julianpetriv Your example project isn't an SDK style project and so therefore will not work. You should create an SDK-style csproj instead, and then add the following to it:

```xml
<PropertyGroup>
  <LangVersion>latest</LangVersion>
</PropertyGroup>
```

**Comment by julianpetriv** [comment] 2024-01-26 10:15
Thanks for sugestion! I will try and let you know if it worked

**Comment by TimothyMakkison** [comment] 2024-01-26 18:48
> Your example project isn't an SDK style project and so therefore will not work. 

Is it worth updating the docs?

**Comment by latonz** [comment] 2024-02-08 01:19
Closing this as no more updates were provided. Looks like it works with a sdk-style projects. Feel free to reopen if the issue persists or new information can be provided.
@TimothyMakkison I think this is a general requirement for source generators. We can add it to the documentation if it comes up again...

**Closed by latonz** 2024-02-08 01:19 UTC
Labels: bug
