### ISSUE TITLE
Support additional parameter value during mapping

### ISSUE THREAD

**Issue by ChaseFlorell** [riok/mapperly#1197] opened 2024-03-22 16:27 UTC
**Is your feature request related to a problem? Please describe.**
I have DTO to Domain object mappings that also have additional context required for the domain to function correctly

**Describe the solution you'd like**
I'd like to be able to hand off additional parameters to the mapping function for use within the mapping

```csharp
[Mapper]
public partial class CarMapper
{
    public partial Car ToCar(CarDto car, ICarContext carContext);
}

public record CarDto(int Wheels);

public class Car
{
    public Car(int wheels, ICarContext carContext)
    {
        Wheels = wheels;
        _carContext = carContext;
    }
    public int Wheels { get; }
    private readonly ICarContext _carContext;
}
```

```csharp
// Relevant new / adjusted API surface
    public partial class CarMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.4.0.0")]
        public partial global::Car? ToCar(global::CarDto? carDto, ICarContext carContext)
        {
            if (carDto == null)
            {
                return default;
             }
             var target = new global::Car(CarDto.Wheels, carContext);
             return target;
        }
```

**Describe alternatives you've considered**
I don't know what alternatives there might be other than a manual mapping, I'm new to this library.

**Additional context**
N/A

**Comment by latonz** [comment] 2024-03-22 16:43
Duplicate of https://github.com/riok/mapperly/issues/103

**Closed by latonz** 2024-03-22 16:43 UTC
Labels: enhancement
