### ISSUE TITLE
Not discovering map when parent takes generic type and is located on different assembly

### ISSUE THREAD

**Issue by devtekve** [riok/mapperly#1267] opened 2024-05-05 10:06 UTC
**Describe the bug**
Mapperly is not generating mappings when the generic class is located in a different assembly. The same class with generic on the same assembly does generate the mappings as expected.

**Declaration code**
```csharp
// START ASSEMBLY A
namespace AssemblyA_NamespaceA
{
    public class MyModel
    {
        public DateTime DateTime { get; set; }
    }

    public class MyEntity
    {
        public long DateTime { get; set; }
    }

    [Mapper]
    public partial class MyMapper : AssemblyB_NamespaceB.BaseMapper<string>
    {
        public partial MyModel MapEntityToModel(MyEntity source);
        public partial MyEntity MapModelToEntity(MyModel source);
    }
}
// END OF ASSEMBLY A

// START ASSEMBLY B
namespace AssemblyB_NamespaceB
{
    public abstract class BaseMapper<T>
    {
        public DateTime MapUnixToDatetime(long unix)
        {
            return DateTimeOffset.FromUnixTimeSeconds(unix).DateTime;
        }

        public long MapDatetimeToUnix(DateTime datetime)
        {
            return ((DateTimeOffset)datetime).ToUnixTimeSeconds();
        }
    }
}
// END OF ASSEMBLY B
```

**Actual relevant generated code**
```csharp
// <auto-generated />
#nullable enable
namespace AssemblyA_NamespaceA
{
    public partial class MyMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.5.1.0")]
        public partial global::AssemblyA_NamespaceA.MyModel MapEntityToModel(global::AssemblyA_NamespaceA.MyEntity source)
        {
            var target = new global::AssemblyA_NamespaceA.MyModel();
            target.DateTime = new global::System.DateTime(source.DateTime);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.5.1.0")]
        public partial global::AssemblyA_NamespaceA.MyEntity MapModelToEntity(global::AssemblyA_NamespaceA.MyModel source)
        {
            var target = new global::AssemblyA_NamespaceA.MyEntity();
            return target;
        }
    }
}
```

**Expected relevant generated code**
```csharp
// <auto-generated />
#nullable enable
namespace AssemblyA_NamespaceA
{
    public partial class MyMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.5.1.0")]
        public partial global::AssemblyA_NamespaceA.MyModel MapEntityToModel(global::AssemblyA_NamespaceA.MyEntity source)
        {
            var target = new global::AssemblyA_NamespaceA.MyModel();
            target.DateTime = MapUnixToDatetime(source.DateTime); // Note that it calls the defined method on the BaseMapper as expected
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.5.1.0")]
        public partial global::AssemblyA_NamespaceA.MyEntity MapModelToEntity(global::AssemblyA_NamespaceA.MyModel source)
        {
            var target = new global::AssemblyA_NamespaceA.MyEntity();
            target.DateTime = MapDatetimeToUnix(source.DateTime); // Note that it calls the defined method on the BaseMapper as expected
            return target;
        }
    }
}
```

**Environment:**
- Mapperly Version: `3.5.1`
- Nullable reference types: `enabled`
- .NET Version: `.NET 8.0.201`
- Target Framework: `.net8.0`
- Compiler Version: `4.9.0-3.24067.18 (4fc721bb)`
- C# Language Version: `12.0`
- IDE: `JetBrains Rider 2024.1.1 Build #RD-241.14494.325, built on April 16, 2024`
- OS: `macOS Sonoma 14.3.1 (23D60) (m1 pro)`

**Additional context**
The following is the code used to generate the expected result. You can copy & paste on a new .cs file. 
```c#
using AssemblyA_NamespaceB;
using Riok.Mapperly.Abstractions;

namespace AssemblyA_NamespaceA
{
    public class MyModel
    {
        public DateTime DateTime { get; set; }
    }

    public class MyEntity
    {
        public long DateTime { get; set; }
    }

    [Mapper]
    public partial class MyMapper : BaseMapper<string>
    {
        public partial MyModel MapEntityToModel(MyEntity source);
        public partial MyEntity MapModelToEntity(MyModel source);
    }
}


namespace AssemblyA_NamespaceB
{
    public abstract class BaseMapper<T>
    {
        public DateTime MapUnixToDatetime(long unix)
        {
            return DateTimeOffset.FromUnixTimeSeconds(unix).DateTime;
        }

        public long MapDatetimeToUnix(DateTime datetime)
        {
            return ((DateTimeOffset)datetime).ToUnixTimeSeconds();
        }
    }
}
``` 

This also feels similar to the issue reported here https://github.com/riok/mapperly/issues/625. I've tested forcing "internals visible to", I've tested with different namespace combinations (trying to make it "fail" on the same assembly) to no avail.

I've also tested it on `3.6.0-next.1` and the issue is present there too.

**Comment by latonz** [comment] 2024-05-05 23:56
I cannot reproduce this, neither with `3.5.1` nor with `3.6.0-next.1`... Mapperly generates exactly the code you posted in `Expected relevant generated code` (except for the comments of course)... Can you create a minimal repro project on GitHub including a `global.json` file selecting the correct .NET SDK? Thanks 😊

**Comment by devtekve** [comment] 2024-05-06 07:46
I am baffled. I just tested and when I am on a clean brand new repo. it works exactly as expected. But when it is together with all my other code, things stop working as expected. 

I even started removing all my actual code leaving just the sample code I submitted and at some point it started working as expected. I am going to start my regular working hours in a bit (the failure happened on a hobby project) so give me a little bit of time to collect more info after work and share it with you, hopefully by EoD.

**Comment by devtekve** [comment] 2024-05-06 15:10
I have not been able to reliable replicate it, its been a bit hit and miss. It works as expected when it's not part of a much bigger solution :( it might take me a while to really nail it down but once I do I will report back. So far it feels like an edge case if I am honest, and most likely something **I** am doing wrong. So feel free to close this to avoid confusing people :D 

PS: I **love** mapperly <3

**Comment by latonz** [comment] 2024-05-06 15:13
Thanks for the feedback 😊 I'll close this for now... Feel free to comment with new insights and I will reopen the issue.

**Closed by latonz** 2024-05-06 15:13 UTC
Labels: bug

**Comment by devtekve** [comment] 2024-05-06 15:40
For completeness, I believe that rider was being the one messing up, either that or my filesystem. But the generated source file might've been outdated some of the times I was checking it, and it was not obvious that was the case. I don't think there was anything inherently wrong with `mapperly` but rather it was really something going on on my setup. 

I did try a lot of things, and sometimes on quick succession, thinking the generated file was up to date (visually), but in reality it might've not been. I came to that realization after setting breakpoints on the implementations on the abstract class, even though rider was "convinced" there were 0 usages for them... 

One thing I don't know if it's helping, but I am afraid to change it and have a panic attack 🤣  is that I set `<MapperlyAbstractionsScope>runtime</MapperlyAbstractionsScope>` on the library were those abstract definitions are made and I am leveraging attributes from there. My actual implementation is a bit more complex that the samples that I added. I would like to share what and why I am doing it, and how is mapperly helping there. Where's a good place to do that? Just wanting to share some code snippets. Is there a discord or is the community GitHub only? Thanks again and sorry for the waste of time!!!

**Comment by latonz** [comment] 2024-05-07 13:11
That‘s strange. If you are unsure whether you are vieweing the latest generated file in your IDE, just use your terminal only and emit the generated file ([docs](https://mapperly.riok.app/docs/configuration/generated-source/)) and check them on the file system. 

under the hood `<MapperlyAbstractionsScope>runtime</MapperlyAbstractionsScope>` only sets an MSBuild-Constant which is used by conditional attributes on the Mapperly API attributes. You can always set/unset this without too much impact. You need this if you want to access the Mapperly attributes during runtime (e.g. via reflection) or if parts of your mapper declaration reside in another assembly and the attributes of that part is relevant.

Currently we don‘t have a discord or a similar communication channel. The main reason for this  is that we want to keep the support effort for this project on a reasonable level. You can just create Gists oder a GitHub repo with your code snippets and share them here (if related to this issue) or in a GH discussion.

PS: thank you for your sponsoring, this helps us maintaining the project ❤️
