### ISSUE TITLE
Projections are ignoring the MapProperty attribute

### ISSUE THREAD

**Issue by chrisevans9629** [riok/mapperly#861] opened 2023-11-02 14:44 UTC
**Describe the bug**

A map property attribute is needed if properties have different names in a projection. When I add the attribute, it doesn't seem to do anything, while it does work if it's not a projection. If I add a regular mapping for the same types, then the regular mapping works AND the projection works!
 
**To Reproduce**

1. Create Dto and model classes with a property with mismatching names
2. Create a mapper with ONLY a IQueryable projection.
3. Add the Map property attribute to the projection.

```csharp
public class ModelT
{
    public double Weight { get; set; }
}

public class ModelTDto
{
    public double Mass { get; set; }
}

[Mapper]
public partial class CarMapper
{
    [MapProperty(nameof(@ModelT.Weight), nameof(@ModelTDto.Mass))]
    public partial IQueryable<ModelTDto> Project(IQueryable<ModelT> query);

    //uncomment this code to make this work!
    //[MapProperty(nameof(@ModelT.Weight), nameof(@ModelTDto.Mass))]
    //public partial ModelTDto Dto(ModelT dto);
}
```

Result:
```csharp
    public partial class CarMapper
    {
        public partial global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelTDto> Project(global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelT> query)
        {
#nullable disable
            return System.Linq.Queryable.Select(query, x => new global::Moonshot.Agency.User.Mappers.ModelTDto());
#nullable enable
        }
    }
```

Result when other mapper is uncommented:
```csharp
    public partial class CarMapper
    {
        public partial global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelTDto> Project(global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelT> query)
        {
#nullable disable
            return System.Linq.Queryable.Select(query, x => new global::Moonshot.Agency.User.Mappers.ModelTDto()
            {
                Mass = x.Weight,
            });
#nullable enable
        }

        public partial global::Moonshot.Agency.User.Mappers.ModelTDto Dto(global::Moonshot.Agency.User.Mappers.ModelT dto)
        {
            var target = new global::Moonshot.Agency.User.Mappers.ModelTDto();
            target.Mass = dto.Weight;
            return target;
        }
    }
```

**Expected behavior**

I would expect this to work even if the "Dto" method was not specified, like this:
```csharp
    public partial class CarMapper
    {
        public partial global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelTDto> Project(global::System.Linq.IQueryable<global::Moonshot.Agency.User.Mappers.ModelT> query)
        {
#nullable disable
            return System.Linq.Queryable.Select(query, x => new global::Moonshot.Agency.User.Mappers.ModelTDto()
            {
                Mass = x.Weight,
            });
#nullable enable
        }

    }
```

**Code snippets**
If applicable, add code snippets to help explain your problem.

**Environment (please complete the following information):**
- Mapperly Version: 3.3.0-next.2
- .NET Version: netstandard2.1
- Target Framework: .net5.0
- IDE: Version 17.7.4
- OS: Windows 11 Enterprise  Version 10.0.22621 Build 22621

**Comment by CommonGuy** [comment] 2023-11-02 14:54
This is by design, as shown in the documentation: https://mapperly.riok.app/docs/configuration/queryable-projections/#property-configurations

**Comment by chrisevans9629** [comment] 2023-11-02 15:12
Ah, gotcha. Do you know if there is a way to add logic to the projection? For example, if I had a car types in the database, something like below. I know you can add logic before and after the mapping, but that is more complicated with projections, as you can't modify with a select with essentially mapping twice. This is what I'm essentially trying to do (I can create another issue if that makes sense, but maybe I'm just missing something in the docs):

```csharp
public class Car
{
    public double Weight { get; set; }
    public ModelT ModelT {get;set;}
    public ModelB ModelB {get;set;}
}

public class CarDto
{
    public double Mass { get; set; }
    public string CarType {get;set;}
}

[Mapper]
public partial class CarMapper
{
    public partial IQueryable<ModelTDto> Project(IQueryable<ModelT> query);
    
    [MapProperty(nameof(@Car.Weight), nameof(@CarDto.Mass))]
    [MapProperty("MethodNameToComputeCarType", nameof(@CarDto.CarType))]
    public partial ModelTDto Dto(ModelT dto);
  
  //essentially, trying to apply some logic to a specific property
   public bool MethodNameToComputeCarType(Car c) => c.ModelT != null ? "ModelT" : "ModelB";
}
```

**Comment by CommonGuy** [comment] 2023-11-02 15:27
@chrisevans9629 No, something like that is not yet supported. I currently also can't think of a workaround...

Please open a new issue so we can track this correctly :)

**Comment by TimothyMakkison** [comment] 2023-11-02 15:48
> This is by design, as shown in the documentation

Is there a reason why or is this a design limitation? 
I feel like ignoring members and `MapProperty` should be possible.

**Comment by CommonGuy** [comment] 2023-11-02 15:51
@TimothyMakkison If I remember correctly, the main reason was that it could get confusing if you had an IQueryable mapping plus a "normal" mapping method with the same types, but different configurations.

This probably needs to be documented better and may change in the future, if we find a good approach to this problem.

**Comment by chrisevans9629** [comment] 2023-11-02 17:11
Could just be a warning where if you put a MapProperty on the IQueryable, it could say "This will be ignored. Please create a mapper for type A -> B with the desired attributes.

**Comment by latonz** [comment] 2023-11-04 11:33
Created #868 to track this. Closing this, as the described behaviour is by design.

**Closed by latonz** 2023-11-04 11:33 UTC
